name: CI pipeline
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  analytics-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install frontend dependencies
        run: cd analytics-app && npm install --omit=optional
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install backend dependencies
        run: cd backend && npm install --omit=optional

